
// Generated by Cadence Genus(TM) Synthesis Solution GENUS15.20 - 15.20-p004_1
// Generated on: May 26 2025 00:05:29

// Verification Directory fv/synth_wrapper 

module alu(clk, rst_n, a, b, op, result, carry);
  input clk, rst_n;
  input [3:0] a, b;
  input [2:0] op;
  output [3:0] result;
  output carry;
  wire clk, rst_n;
  wire [3:0] a, b;
  wire [2:0] op;
  wire [3:0] result;
  wire carry;
  wire n_0, n_6, n_7, n_8, n_9, n_10, n_11, n_12;
  wire n_13, n_14, n_15, n_16, n_17, n_18, n_24, n_25;
  wire n_27, n_28, n_29, n_30, n_32, n_37, n_38, n_41;
  wire n_45, n_46, n_48, n_49, n_50, n_52, n_53, n_54;
  wire n_56, n_58, n_59, n_60, n_61, n_65, n_66, n_67;
  wire n_69, n_70, n_71, n_76, n_80, n_81, n_82, n_86;
  wire n_88, n_89, n_91, n_92, n_94, n_99, n_101, n_102;
  wire n_103, n_106, n_107, n_109, n_123, n_125, n_127, n_131;
  wire n_136, n_137, n_138, n_142, n_143, n_144, n_154, n_160;
  wire n_163, n_165, n_167, n_168, n_169, n_170, n_171, n_173;
  wire n_174, n_176, n_178, n_179, n_180, n_183, n_184, n_185;
  wire n_192, n_195, n_200, n_201, n_202, n_203, n_204, n_205;
  wire n_207, n_208, n_210, n_212, n_217, n_218, n_219, n_220;
  wire n_222, n_228, n_230, n_232, n_233, n_234, n_235, n_236;
  wire n_238, n_239, n_240, n_241, n_242;
  sky130_fd_sc_hd__o221ai_1 g2777(.A1 (n_59), .A2 (n_102), .B1 (n_27),
       .B2 (n_138), .C1 (n_109), .Y (carry));
  sky130_fd_sc_hd__nand2b_1 g2778(.A_N (n_60), .B (n_144), .Y (n_109));
  sky130_fd_sc_hd__o2111ai_1 g2779(.A1 (n_17), .A2 (n_228), .B1
       (n_169), .C1 (n_86), .D1 (n_103), .Y (result[2]));
  sky130_fd_sc_hd__nand2_1 g2780(.A (n_106), .B (n_60), .Y (n_107));
  sky130_fd_sc_hd__nand2_1 g2781(.A (n_102), .B (n_101), .Y (n_106));
  sky130_fd_sc_hd__a21oi_2 g2784(.A1 (n_89), .A2 (n_220), .B1 (n_99),
       .Y (n_103));
  sky130_fd_sc_hd__nand2_1 g2785(.A (n_240), .B (n_220), .Y (n_102));
  sky130_fd_sc_hd__nand2b_1 g2786(.A_N (n_138), .B (n_203), .Y (n_101));
  sky130_fd_sc_hd__o211ai_2 g2788(.A1 (n_138), .A2 (n_235), .B1 (n_71),
       .C1 (n_66), .Y (n_99));
  sky130_fd_sc_hd__o2111ai_1 g2793(.A1 (n_52), .A2 (n_58), .B1 (n_69),
       .C1 (n_81), .D1 (n_92), .Y (result[0]));
  sky130_fd_sc_hd__nor2_1 g2794(.A (n_195), .B (n_88), .Y (n_94));
  sky130_fd_sc_hd__o21a_1 g2796(.A1 (n_230), .A2 (n_70), .B1 (n_167),
       .X (n_92));
  sky130_fd_sc_hd__o22a_1 g2797(.A1 (n_61), .A2 (n_82), .B1 (a[1]), .B2
       (n_46), .X (n_91));
  sky130_fd_sc_hd__xor2_1 g2799(.A (n_234), .B (n_212), .X (n_89));
  sky130_fd_sc_hd__o211ai_2 g2800(.A1 (n_45), .A2 (n_60), .B1 (n_49),
       .C1 (n_173), .Y (n_88));
  sky130_fd_sc_hd__a21oi_1 g2802(.A1 (n_176), .A2 (n_6), .B1 (n_76), .Y
       (n_86));
  sky130_fd_sc_hd__nor2_1 g2805(.A (n_174), .B (n_176), .Y (n_82));
  sky130_fd_sc_hd__a21oi_1 g2806(.A1 (n_176), .A2 (n_0), .B1 (n_154),
       .Y (n_81));
  sky130_fd_sc_hd__nand2_1 g2807(.A (n_67), .B (n_30), .Y (n_80));
  sky130_fd_sc_hd__o22ai_1 g2811(.A1 (n_45), .A2 (n_234), .B1 (n_7),
       .B2 (n_46), .Y (n_76));
  sky130_fd_sc_hd__or2_1 g2818(.A (n_54), .B (n_52), .X (n_71));
  sky130_fd_sc_hd__and2_0 g2819(.A (n_58), .B (n_37), .X (n_70));
  sky130_fd_sc_hd__a21o_1 g2820(.A1 (n_45), .A2 (n_137), .B1 (n_38), .X
       (n_69));
  sky130_fd_sc_hd__o21ai_0 g2822(.A1 (n_131), .A2 (n_11), .B1 (n_24),
       .Y (n_67));
  sky130_fd_sc_hd__nand3b_1 g2823(.A_N (n_9), .B (n_48), .C (a[1]), .Y
       (n_66));
  sky130_fd_sc_hd__a21oi_1 g2824(.A1 (n_11), .A2 (n_131), .B1 (n_61),
       .Y (n_65));
  sky130_fd_sc_hd__inv_1 g2830(.A (n_179), .Y (n_61));
  sky130_fd_sc_hd__ha_1 g2832(.A (a[3]), .B (n_15), .COUT (n_59), .SUM
       (n_60));
  sky130_fd_sc_hd__nor2_1 g2833(.A (n_8), .B (n_138), .Y (n_56));
  sky130_fd_sc_hd__nand2_1 g2835(.A (n_192), .B (b[0]), .Y (n_9));
  sky130_fd_sc_hd__nand2_1 g2836(.A (n_192), .B (a[0]), .Y (n_58));
  sky130_fd_sc_hd__a21oi_1 g2839(.A1 (n_160), .A2 (n_6), .B1 (n_176),
       .Y (n_50));
  sky130_fd_sc_hd__o21ai_1 g2840(.A1 (b[3]), .A2 (a[3]), .B1 (n_176),
       .Y (n_49));
  sky130_fd_sc_hd__o221ai_1 g2841(.A1 (a[2]), .A2 (b[1]), .B1 (a[0]),
       .B2 (n_127), .C1 (n_29), .Y (n_54));
  sky130_fd_sc_hd__nand2_1 g2842(.A (n_48), .B (b[0]), .Y (n_53));
  sky130_fd_sc_hd__nand4_1 g2843(.A (n_222), .B (op[2]), .C (n_12), .D
       (op[1]), .Y (n_52));
  sky130_fd_sc_hd__nor2_1 g2844(.A (n_18), .B (n_163), .Y (n_48));
  sky130_fd_sc_hd__nand2_1 g2846(.A (n_25), .B (n_222), .Y (n_46));
  sky130_fd_sc_hd__nand2_1 g2847(.A (n_25), .B (n_18), .Y (n_45));
  sky130_fd_sc_hd__a21oi_1 g2852(.A1 (n_12), .A2 (a[0]), .B1 (n_210),
       .Y (n_38));
  sky130_fd_sc_hd__nand3_1 g2853(.A (n_30), .B (n_131), .C (n_7), .Y
       (n_37));
  sky130_fd_sc_hd__xnor2_2 g2854(.A (a[1]), .B (n_127), .Y (n_10));
  sky130_fd_sc_hd__nand2_2 g2855(.A (n_29), .B (n_127), .Y (n_41));
  sky130_fd_sc_hd__clkinv_1 g2860(.A (n_8), .Y (n_32));
  sky130_fd_sc_hd__clkbuf_1 g2861(.A (n_178), .X (n_8));
  sky130_fd_sc_hd__clkbuf_1 g2863(.A (n_29), .X (n_30));
  sky130_fd_sc_hd__nand2_1 g2864(.A (n_16), .B (b[2]), .Y (n_28));
  sky130_fd_sc_hd__nor2_2 g2870(.A (b[3]), .B (b[2]), .Y (n_29));
  sky130_fd_sc_hd__nand2_1 g2874(.A (a[3]), .B (b[3]), .Y (n_27));
  sky130_fd_sc_hd__nor2b_1 g2876(.A (op[1]), .B_N (op[2]), .Y (n_25));
  sky130_fd_sc_hd__nand2_1 g2877(.A (b[1]), .B (a[1]), .Y (n_24));
  sky130_fd_sc_hd__inv_1 g2882(.A (n_7), .Y (n_17));
  sky130_fd_sc_hd__buf_1 g2884(.A (a[2]), .X (n_7));
  sky130_fd_sc_hd__inv_2 g2885(.A (a[2]), .Y (n_16));
  sky130_fd_sc_hd__inv_1 g2887(.A (b[3]), .Y (n_15));
  sky130_fd_sc_hd__inv_2 g2888(.A (b[2]), .Y (n_14));
  sky130_fd_sc_hd__buf_1 g2890(.A (b[2]), .X (n_6));
  sky130_fd_sc_hd__inv_2 g2892(.A (a[1]), .Y (n_13));
  sky130_fd_sc_hd__inv_2 g2893(.A (b[0]), .Y (n_12));
  sky130_fd_sc_hd__inv_1 g2894(.A (a[3]), .Y (n_11));
  sky130_fd_sc_hd__nand2b_1 g2902(.A_N (a[0]), .B (n_12), .Y (n_0));
  sky130_fd_sc_hd__clkbuf_2 fopt(.A (n_10), .X (n_123));
  sky130_fd_sc_hd__inv_2 fopt2904(.A (n_192), .Y (n_125));
  sky130_fd_sc_hd__inv_4 fopt2906(.A (b[1]), .Y (n_127));
  sky130_fd_sc_hd__clkbuf_1 fopt2910(.A (b[1]), .X (n_131));
  sky130_fd_sc_hd__inv_1 g2911(.A (n_136), .Y (n_137));
  sky130_fd_sc_hd__nand2_2 g2913(.A (n_136), .B (n_18), .Y (n_138));
  sky130_fd_sc_hd__nor2_1 g2915(.A (op[2]), .B (op[1]), .Y (n_136));
  sky130_fd_sc_hd__o221ai_1 g2916(.A1 (n_32), .A2 (n_138), .B1 (n_210),
       .B2 (n_143), .C1 (n_45), .Y (n_142));
  sky130_fd_sc_hd__o21ai_1 g2918(.A1 (n_59), .A2 (n_143), .B1 (n_101),
       .Y (n_144));
  sky130_fd_sc_hd__o22ai_1 g2928(.A1 (a[0]), .A2 (n_46), .B1 (n_171),
       .B2 (n_8), .Y (n_154));
  sky130_fd_sc_hd__inv_1 g2934(.A (n_171), .Y (n_160));
  sky130_fd_sc_hd__nand2_1 g2938(.A (op[2]), .B (op[1]), .Y (n_163));
  sky130_fd_sc_hd__nand2_1 g2939(.A (n_168), .B (n_7), .Y (n_165));
  sky130_fd_sc_hd__nand3b_1 g2942(.A_N (n_185), .B (n_168), .C (b[0]),
       .Y (n_167));
  sky130_fd_sc_hd__nand3b_1 g2943(.A_N (n_9), .B (n_168), .C (a[3]), .Y
       (n_169));
  sky130_fd_sc_hd__o22a_1 g2945(.A1 (a[3]), .A2 (n_46), .B1 (n_27), .B2
       (n_171), .X (n_173));
  sky130_fd_sc_hd__nand2_2 g2947(.A (n_170), .B (op[1]), .Y (n_171));
  sky130_fd_sc_hd__inv_2 g2948(.A (op[2]), .Y (n_170));
  sky130_fd_sc_hd__nor2_1 g2949(.A (n_24), .B (n_171), .Y (n_174));
  sky130_fd_sc_hd__nor2_2 g2951(.A (n_171), .B (n_18), .Y (n_176));
  sky130_fd_sc_hd__nand2_2 g2953(.A (a[0]), .B (b[0]), .Y (n_178));
  sky130_fd_sc_hd__nand2_2 g2954(.A (n_127), .B (n_13), .Y (n_179));
  sky130_fd_sc_hd__inv_2 g2957(.A (n_178), .Y (n_180));
  sky130_fd_sc_hd__nand3_1 g2959(.A (n_184), .B (n_183), .C (n_238), .Y
       (result[1]));
  sky130_fd_sc_hd__o22a_1 g2960(.A1 (n_165), .A2 (n_9), .B1 (n_53), .B2
       (n_58), .X (n_183));
  sky130_fd_sc_hd__a21oi_2 g2961(.A1 (n_142), .A2 (n_123), .B1 (n_219),
       .Y (n_184));
  sky130_fd_sc_hd__nand2_1 g2963(.A (n_65), .B (n_30), .Y (n_185));
  sky130_fd_sc_hd__inv_2 fopt2967(.A (n_41), .Y (n_192));
  sky130_fd_sc_hd__o221ai_1 g2968(.A1 (n_52), .A2 (n_80), .B1 (n_54),
       .B2 (n_53), .C1 (n_239), .Y (n_195));
  sky130_fd_sc_hd__o2bb2ai_1 g60(.A1_N (n_7), .A2_N (n_6), .B1 (n_234),
       .B2 (n_202), .Y (n_203));
  sky130_fd_sc_hd__inv_2 g61(.A (n_201), .Y (n_202));
  sky130_fd_sc_hd__nand2_2 g62(.A (n_200), .B (n_24), .Y (n_201));
  sky130_fd_sc_hd__nand2_2 g63(.A (n_179), .B (n_180), .Y (n_200));
  sky130_fd_sc_hd__nand4_1 g203(.A (n_107), .B (n_94), .C (n_205), .D
       (n_208), .Y (result[3]));
  sky130_fd_sc_hd__nand2b_1 g206(.A_N (n_203), .B (n_204), .Y (n_205));
  sky130_fd_sc_hd__nor2_1 g207(.A (n_138), .B (n_60), .Y (n_204));
  sky130_fd_sc_hd__nand2b_1 g204(.A_N (n_240), .B (n_207), .Y (n_208));
  sky130_fd_sc_hd__nor2_1 g208(.A (n_143), .B (n_60), .Y (n_207));
  sky130_fd_sc_hd__o21ai_2 g34(.A1 (n_210), .A2 (n_10), .B1 (n_242), .Y
       (n_212));
  sky130_fd_sc_hd__nor2_2 g35(.A (a[0]), .B (n_12), .Y (n_210));
  sky130_fd_sc_hd__nand2_1 g2973(.A (n_91), .B (n_218), .Y (n_219));
  sky130_fd_sc_hd__o21bai_1 g2974(.A1 (n_217), .A2 (n_56), .B1_N
       (n_123), .Y (n_218));
  sky130_fd_sc_hd__nor2b_1 g2975(.A (n_143), .B_N (n_210), .Y (n_217));
  sky130_fd_sc_hd__nand2_2 g38(.A (n_136), .B (n_222), .Y (n_143));
  sky130_fd_sc_hd__inv_2 g2976(.A (n_143), .Y (n_220));
  sky130_fd_sc_hd__inv_2 g2977(.A (n_18), .Y (n_222));
  sky130_fd_sc_hd__inv_2 g2978(.A (op[0]), .Y (n_18));
  sky130_fd_sc_hd__and2_1 g23(.A (n_50), .B (n_241), .X (n_228));
  sky130_fd_sc_hd__nor2_2 g29(.A (n_222), .B (n_163), .Y (n_168));
  sky130_fd_sc_hd__nand3b_1 g2982(.A_N (n_163), .B (n_12), .C (n_18),
       .Y (n_230));
  sky130_fd_sc_hd__o2bb2ai_2 g2983(.A1_N (n_234), .A2_N (n_202), .B1
       (n_234), .B2 (n_202), .Y (n_235));
  sky130_fd_sc_hd__inv_4 g2984(.A (n_233), .Y (n_234));
  sky130_fd_sc_hd__nand2_2 g2985(.A (n_232), .B (n_28), .Y (n_233));
  sky130_fd_sc_hd__nand2_2 g2986(.A (n_14), .B (a[2]), .Y (n_232));
  sky130_fd_sc_hd__o21ai_1 g2(.A1 (n_125), .A2 (n_52), .B1 (n_230), .Y
       (n_236));
  sky130_fd_sc_hd__nand2b_1 g2988(.A_N (n_185), .B (n_236), .Y (n_238));
  sky130_fd_sc_hd__nand3b_1 g2989(.A_N (n_230), .B (n_192), .C (a[3]),
       .Y (n_239));
  sky130_fd_sc_hd__a21boi_1 g2990(.A1 (n_212), .A2 (n_234), .B1_N
       (n_232), .Y (n_240));
  sky130_fd_sc_hd__nand3b_1 g2991(.A_N (n_125), .B (n_168), .C (n_12),
       .Y (n_241));
  sky130_fd_sc_hd__or2_1 g2992(.A (n_13), .B (b[1]), .X (n_242));
endmodule

module synth_wrapper(clk, rst_n, a, b, op, result, carry);
  input clk, rst_n;
  input [3:0] a, b;
  input [2:0] op;
  output [3:0] result;
  output carry;
  wire clk, rst_n;
  wire [3:0] a, b;
  wire [2:0] op;
  wire [3:0] result;
  wire carry;
  wire [3:0] a_reg;
  wire [3:0] b_reg;
  wire [2:0] op_reg;
  wire UNCONNECTED, UNCONNECTED0, UNCONNECTED1, UNCONNECTED2,
       UNCONNECTED_HIER_Z, carry_reg_70, n_0, n_1;
  wire n_2, n_3, n_4, n_5, n_6, n_8, n_9, n_10;
  wire n_11, n_12, n_13, n_14, n_15, n_16, n_17, n_18;
  wire n_19, n_20, n_21, n_22, n_23, n_24, n_25, n_26;
  wire n_27, n_28, n_29, n_30, n_31, n_32, n_33, n_34;
  wire n_68, \result_reg[0]_58 , \result_reg[1]_59 , \result_reg[2]_60
       , \result_reg[3]_61 ;
  alu alu(.clk (clk), .rst_n (UNCONNECTED_HIER_Z), .a (a_reg), .b
       ({b_reg[3:2], n_68, b_reg[0]}), .op (op_reg), .result
       ({\result_reg[3]_61 , \result_reg[2]_60 , \result_reg[1]_59 ,
       \result_reg[0]_58 }), .carry (carry_reg_70));
  sky130_fd_sc_hd__dfbbp_1 \b_reg_reg[1] (.RESET_B (n_20), .SET_B
       (n_23), .CLK (clk), .D (b[1]), .Q (UNCONNECTED), .Q_N (n_28));
  sky130_fd_sc_hd__dfbbp_1 \b_reg_reg[0] (.RESET_B (n_13), .SET_B
       (n_22), .CLK (clk), .D (b[0]), .Q (UNCONNECTED0), .Q_N (n_27));
  sky130_fd_sc_hd__dfbbp_1 \a_reg_reg[0] (.RESET_B (n_5), .SET_B (n_9),
       .CLK (clk), .D (a[0]), .Q (UNCONNECTED1), .Q_N (n_31));
  sky130_fd_sc_hd__dfbbp_1 \b_reg_reg[2] (.RESET_B (n_21), .SET_B
       (n_19), .CLK (clk), .D (b[2]), .Q (b_reg[2]), .Q_N (n_29));
  sky130_fd_sc_hd__dfbbp_1 \b_reg_reg[3] (.RESET_B (n_18), .SET_B
       (n_17), .CLK (clk), .D (b[3]), .Q (b_reg[3]), .Q_N (n_30));
  sky130_fd_sc_hd__dfbbp_1 \op_reg_reg[0] (.RESET_B (n_1), .SET_B
       (n_16), .CLK (clk), .D (op[0]), .Q (op_reg[0]), .Q_N (n_24));
  sky130_fd_sc_hd__dfbbp_1 \op_reg_reg[1] (.RESET_B (n_10), .SET_B
       (n_11), .CLK (clk), .D (op[1]), .Q (op_reg[1]), .Q_N (n_25));
  sky130_fd_sc_hd__dfbbp_1 \op_reg_reg[2] (.RESET_B (n_14), .SET_B
       (n_12), .CLK (clk), .D (op[2]), .Q (op_reg[2]), .Q_N (n_26));
  sky130_fd_sc_hd__dfbbp_1 \a_reg_reg[1] (.RESET_B (n_8), .SET_B (n_6),
       .CLK (clk), .D (a[1]), .Q (UNCONNECTED2), .Q_N (n_32));
  sky130_fd_sc_hd__dfbbp_1 \a_reg_reg[2] (.RESET_B (n_4), .SET_B (n_3),
       .CLK (clk), .D (a[2]), .Q (a_reg[2]), .Q_N (n_33));
  sky130_fd_sc_hd__dfbbp_1 \a_reg_reg[3] (.RESET_B (n_15), .SET_B
       (n_2), .CLK (clk), .D (a[3]), .Q (a_reg[3]), .Q_N (n_34));
  sky130_fd_sc_hd__dfrtp_1 carry_reg(.RESET_B (rst_n), .CLK (clk), .D
       (carry_reg_70), .Q (carry));
  sky130_fd_sc_hd__dfrtp_1 \result_reg[2] (.RESET_B (rst_n), .CLK
       (clk), .D (\result_reg[2]_60 ), .Q (result[2]));
  sky130_fd_sc_hd__dfrtp_1 \result_reg[0] (.RESET_B (rst_n), .CLK
       (clk), .D (\result_reg[0]_58 ), .Q (result[0]));
  sky130_fd_sc_hd__dfrtp_1 \result_reg[1] (.RESET_B (rst_n), .CLK
       (clk), .D (\result_reg[1]_59 ), .Q (result[1]));
  sky130_fd_sc_hd__dfrtp_1 \result_reg[3] (.RESET_B (rst_n), .CLK
       (clk), .D (\result_reg[3]_61 ), .Q (result[3]));
  sky130_fd_sc_hd__nand2_1 g292(.A (n_0), .B (b[1]), .Y (n_23));
  sky130_fd_sc_hd__nand2_1 g293(.A (n_0), .B (b[0]), .Y (n_22));
  sky130_fd_sc_hd__or2_1 g294(.A (b[2]), .B (rst_n), .X (n_21));
  sky130_fd_sc_hd__or2_1 g295(.A (b[1]), .B (rst_n), .X (n_20));
  sky130_fd_sc_hd__nand2_1 g296(.A (n_0), .B (b[2]), .Y (n_19));
  sky130_fd_sc_hd__or2_1 g297(.A (b[3]), .B (rst_n), .X (n_18));
  sky130_fd_sc_hd__nand2_1 g298(.A (n_0), .B (b[3]), .Y (n_17));
  sky130_fd_sc_hd__nand2_1 g299(.A (n_0), .B (op[0]), .Y (n_16));
  sky130_fd_sc_hd__or2_1 g300(.A (a[3]), .B (rst_n), .X (n_15));
  sky130_fd_sc_hd__or2_1 g301(.A (op[2]), .B (rst_n), .X (n_14));
  sky130_fd_sc_hd__or2_1 g302(.A (b[0]), .B (rst_n), .X (n_13));
  sky130_fd_sc_hd__nand2_1 g303(.A (n_0), .B (op[2]), .Y (n_12));
  sky130_fd_sc_hd__nand2_1 g304(.A (n_0), .B (op[1]), .Y (n_11));
  sky130_fd_sc_hd__or2_1 g305(.A (op[1]), .B (rst_n), .X (n_10));
  sky130_fd_sc_hd__nand2_1 g306(.A (n_0), .B (a[0]), .Y (n_9));
  sky130_fd_sc_hd__or2_1 g307(.A (a[1]), .B (rst_n), .X (n_8));
  sky130_fd_sc_hd__nand2_1 g308(.A (n_0), .B (a[1]), .Y (n_6));
  sky130_fd_sc_hd__or2_1 g309(.A (a[0]), .B (rst_n), .X (n_5));
  sky130_fd_sc_hd__or2_1 g310(.A (a[2]), .B (rst_n), .X (n_4));
  sky130_fd_sc_hd__nand2_1 g311(.A (n_0), .B (a[2]), .Y (n_3));
  sky130_fd_sc_hd__nand2_1 g312(.A (n_0), .B (a[3]), .Y (n_2));
  sky130_fd_sc_hd__or2_1 g313(.A (op[0]), .B (rst_n), .X (n_1));
  sky130_fd_sc_hd__clkinv_2 g315(.A (n_31), .Y (a_reg[0]));
  sky130_fd_sc_hd__clkinv_2 g316(.A (n_32), .Y (a_reg[1]));
  sky130_fd_sc_hd__inv_2 g319(.A (rst_n), .Y (n_0));
  sky130_fd_sc_hd__inv_2 g324(.A (n_27), .Y (b_reg[0]));
  sky130_fd_sc_hd__clkinv_2 fopt(.A (n_28), .Y (n_68));
endmodule

