
// Generated by Cadence Genus(TM) Synthesis Solution GENUS15.20 - 15.20-p004_1
// Generated on: May 26 2025 00:05:25

// Verification Directory fv/synth_wrapper 

module alu(clk, rst_n, a, b, op, result, carry);
  input clk, rst_n;
  input [3:0] a, b;
  input [2:0] op;
  output [3:0] result;
  output carry;
  wire clk, rst_n;
  wire [3:0] a, b;
  wire [2:0] op;
  wire [3:0] result;
  wire carry;
  wire n_0, n_1, n_2, n_3, n_4, n_5, n_6, n_7;
  wire n_8, n_9, n_10, n_11, n_12, n_13, n_14, n_15;
  wire n_16, n_17, n_18, n_19, n_20, n_21, n_22, n_23;
  wire n_24, n_25, n_26, n_27, n_28, n_29, n_30, n_31;
  wire n_32, n_33, n_34, n_35, n_36, n_37, n_38, n_39;
  wire n_40, n_41, n_42, n_43, n_44, n_45, n_46, n_47;
  wire n_48, n_49, n_50, n_51, n_52, n_53, n_54, n_55;
  wire n_56, n_57, n_58, n_59, n_60, n_61, n_62, n_63;
  wire n_64, n_65, n_66, n_67, n_68, n_69, n_70, n_71;
  wire n_72, n_73, n_74, n_75, n_76, n_77, n_78, n_79;
  wire n_80, n_81, n_82, n_83, n_84, n_85, n_86, n_87;
  wire n_88, n_89, n_90, n_91, n_92, n_93, n_94, n_96;
  wire n_97, n_98, n_99, n_101, n_102, n_103, n_104, n_105;
  wire n_106, n_107, n_109;
  sky130_fd_sc_hd__o211ai_2 g2776(.A1 (n_60), .A2 (n_104), .B1 (n_94),
       .C1 (n_107), .Y (result[3]));
  sky130_fd_sc_hd__o221ai_1 g2777(.A1 (n_59), .A2 (n_102), .B1 (n_27),
       .B2 (n_43), .C1 (n_109), .Y (carry));
  sky130_fd_sc_hd__nand2b_1 g2778(.A_N (n_60), .B (n_105), .Y (n_109));
  sky130_fd_sc_hd__o2111ai_1 g2779(.A1 (n_17), .A2 (n_73), .B1 (n_68),
       .C1 (n_86), .D1 (n_103), .Y (result[2]));
  sky130_fd_sc_hd__nand2_1 g2780(.A (n_106), .B (n_60), .Y (n_107));
  sky130_fd_sc_hd__nand2_1 g2781(.A (n_102), .B (n_101), .Y (n_106));
  sky130_fd_sc_hd__o21ai_1 g2782(.A1 (n_59), .A2 (n_40), .B1 (n_101),
       .Y (n_105));
  sky130_fd_sc_hd__o22a_1 g2783(.A1 (n_40), .A2 (n_1), .B1 (n_43), .B2
       (n_98), .X (n_104));
  sky130_fd_sc_hd__a21oi_2 g2784(.A1 (n_89), .A2 (n_39), .B1 (n_99), .Y
       (n_103));
  sky130_fd_sc_hd__nand2_1 g2785(.A (n_1), .B (n_39), .Y (n_102));
  sky130_fd_sc_hd__nand2b_1 g2786(.A_N (n_43), .B (n_98), .Y (n_101));
  sky130_fd_sc_hd__o211ai_1 g2787(.A1 (n_84), .A2 (n_77), .B1 (n_75),
       .C1 (n_97), .Y (result[1]));
  sky130_fd_sc_hd__o211ai_1 g2788(.A1 (n_43), .A2 (n_90), .B1 (n_71),
       .C1 (n_66), .Y (n_99));
  sky130_fd_sc_hd__a21oi_1 g2790(.A1 (n_85), .A2 (n_10), .B1 (n_96), .Y
       (n_97));
  sky130_fd_sc_hd__o2bb2ai_1 g2791(.A1_N (n_6), .A2_N (n_7), .B1 (n_3),
       .B2 (n_83), .Y (n_98));
  sky130_fd_sc_hd__o21ai_1 g2792(.A1 (n_10), .A2 (n_74), .B1 (n_91), .Y
       (n_96));
  sky130_fd_sc_hd__o2111ai_1 g2793(.A1 (n_52), .A2 (n_58), .B1 (n_69),
       .C1 (n_81), .D1 (n_92), .Y (result[0]));
  sky130_fd_sc_hd__nor2_1 g2794(.A (n_88), .B (n_93), .Y (n_94));
  sky130_fd_sc_hd__o221ai_1 g2795(.A1 (n_80), .A2 (n_52), .B1 (n_54),
       .B2 (n_53), .C1 (n_64), .Y (n_93));
  sky130_fd_sc_hd__o21a_1 g2796(.A1 (n_57), .A2 (n_70), .B1 (n_87), .X
       (n_92));
  sky130_fd_sc_hd__o22a_1 g2797(.A1 (n_61), .A2 (n_82), .B1 (a[1]), .B2
       (n_46), .X (n_91));
  sky130_fd_sc_hd__xnor2_1 g2798(.A (n_3), .B (n_83), .Y (n_90));
  sky130_fd_sc_hd__xor2_1 g2799(.A (n_3), .B (n_78), .X (n_89));
  sky130_fd_sc_hd__o211ai_1 g2800(.A1 (n_60), .A2 (n_45), .B1 (n_49),
       .C1 (n_62), .Y (n_88));
  sky130_fd_sc_hd__nand3b_1 g2801(.A_N (n_84), .B (n_47), .C (b[0]), .Y
       (n_87));
  sky130_fd_sc_hd__a21oi_1 g2802(.A1 (n_44), .A2 (n_6), .B1 (n_76), .Y
       (n_86));
  sky130_fd_sc_hd__o221ai_1 g2803(.A1 (n_32), .A2 (n_43), .B1 (n_23),
       .B2 (n_40), .C1 (n_45), .Y (n_85));
  sky130_fd_sc_hd__inv_2 g2804(.A (n_79), .Y (n_83));
  sky130_fd_sc_hd__nor2_1 g2805(.A (n_72), .B (n_44), .Y (n_82));
  sky130_fd_sc_hd__a21oi_1 g2806(.A1 (n_44), .A2 (n_0), .B1 (n_63), .Y
       (n_81));
  sky130_fd_sc_hd__nand2_1 g2807(.A (n_67), .B (n_30), .Y (n_80));
  sky130_fd_sc_hd__nand2_1 g2808(.A (n_65), .B (n_30), .Y (n_84));
  sky130_fd_sc_hd__nand2_1 g2809(.A (n_2), .B (n_24), .Y (n_79));
  sky130_fd_sc_hd__o21a_1 g2810(.A1 (n_55), .A2 (n_52), .B1 (n_57), .X
       (n_77));
  sky130_fd_sc_hd__o22ai_1 g2811(.A1 (n_45), .A2 (n_3), .B1 (n_7), .B2
       (n_46), .Y (n_76));
  sky130_fd_sc_hd__o22a_1 g2812(.A1 (n_51), .A2 (n_9), .B1 (n_53), .B2
       (n_58), .X (n_75));
  sky130_fd_sc_hd__a21oi_1 g2813(.A1 (n_39), .A2 (n_23), .B1 (n_56), .Y
       (n_74));
  sky130_fd_sc_hd__o21a_1 g2814(.A1 (n_41), .A2 (n_57), .B1 (n_50), .X
       (n_73));
  sky130_fd_sc_hd__o21bai_2 g2815(.A1 (n_23), .A2 (n_10), .B1_N (n_20),
       .Y (n_78));
  sky130_fd_sc_hd__nor2_1 g2816(.A (n_24), .B (n_22), .Y (n_72));
  sky130_fd_sc_hd__or2_1 g2818(.A (n_54), .B (n_52), .X (n_71));
  sky130_fd_sc_hd__and2_0 g2819(.A (n_58), .B (n_37), .X (n_70));
  sky130_fd_sc_hd__a21o_1 g2820(.A1 (n_45), .A2 (n_34), .B1 (n_38), .X
       (n_69));
  sky130_fd_sc_hd__nand3b_1 g2821(.A_N (n_9), .B (n_47), .C (a[3]), .Y
       (n_68));
  sky130_fd_sc_hd__o21ai_0 g2822(.A1 (n_5), .A2 (n_11), .B1 (n_24), .Y
       (n_67));
  sky130_fd_sc_hd__nand3b_1 g2823(.A_N (n_9), .B (n_48), .C (a[1]), .Y
       (n_66));
  sky130_fd_sc_hd__a21oi_1 g2824(.A1 (n_11), .A2 (n_5), .B1 (n_61), .Y
       (n_65));
  sky130_fd_sc_hd__nand3b_1 g2825(.A_N (n_57), .B (n_42), .C (a[3]), .Y
       (n_64));
  sky130_fd_sc_hd__o22ai_1 g2826(.A1 (a[0]), .A2 (n_46), .B1 (n_22),
       .B2 (n_8), .Y (n_63));
  sky130_fd_sc_hd__o22a_1 g2827(.A1 (a[3]), .A2 (n_46), .B1 (n_27), .B2
       (n_22), .X (n_62));
  sky130_fd_sc_hd__clkinv_1 g2830(.A (n_35), .Y (n_61));
  sky130_fd_sc_hd__ha_1 g2832(.A (a[3]), .B (n_15), .COUT (n_59), .SUM
       (n_60));
  sky130_fd_sc_hd__nor2_1 g2833(.A (n_8), .B (n_43), .Y (n_56));
  sky130_fd_sc_hd__nand2_1 g2834(.A (n_42), .B (a[1]), .Y (n_55));
  sky130_fd_sc_hd__nand2_1 g2835(.A (n_42), .B (b[0]), .Y (n_9));
  sky130_fd_sc_hd__nand2_2 g2836(.A (n_42), .B (a[0]), .Y (n_58));
  sky130_fd_sc_hd__nand2_1 g2837(.A (n_47), .B (n_12), .Y (n_57));
  sky130_fd_sc_hd__nand2_1 g2838(.A (n_47), .B (n_7), .Y (n_51));
  sky130_fd_sc_hd__a21oi_1 g2839(.A1 (n_21), .A2 (n_6), .B1 (n_44), .Y
       (n_50));
  sky130_fd_sc_hd__o21ai_1 g2840(.A1 (b[3]), .A2 (a[3]), .B1 (n_44), .Y
       (n_49));
  sky130_fd_sc_hd__o221ai_1 g2841(.A1 (a[2]), .A2 (n_5), .B1 (a[0]),
       .B2 (n_4), .C1 (n_29), .Y (n_54));
  sky130_fd_sc_hd__nand2_1 g2842(.A (n_48), .B (b[0]), .Y (n_53));
  sky130_fd_sc_hd__nand4_1 g2843(.A (op[0]), .B (op[2]), .C (n_12), .D
       (op[1]), .Y (n_52));
  sky130_fd_sc_hd__nor2_1 g2844(.A (n_18), .B (n_36), .Y (n_48));
  sky130_fd_sc_hd__nor2_2 g2845(.A (op[0]), .B (n_36), .Y (n_47));
  sky130_fd_sc_hd__nand2_1 g2846(.A (n_25), .B (op[0]), .Y (n_46));
  sky130_fd_sc_hd__nand2_1 g2847(.A (n_25), .B (n_18), .Y (n_45));
  sky130_fd_sc_hd__nor2_4 g2848(.A (n_22), .B (n_18), .Y (n_44));
  sky130_fd_sc_hd__nand2_2 g2849(.A (n_33), .B (n_18), .Y (n_43));
  sky130_fd_sc_hd__inv_2 g2850(.A (n_41), .Y (n_42));
  sky130_fd_sc_hd__inv_2 g2851(.A (n_40), .Y (n_39));
  sky130_fd_sc_hd__a21oi_1 g2852(.A1 (n_12), .A2 (a[0]), .B1 (n_23), .Y
       (n_38));
  sky130_fd_sc_hd__nand3_1 g2853(.A (n_30), .B (n_5), .C (n_7), .Y
       (n_37));
  sky130_fd_sc_hd__xnor2_2 g2854(.A (a[1]), .B (n_4), .Y (n_10));
  sky130_fd_sc_hd__nand2_1 g2855(.A (n_4), .B (n_29), .Y (n_41));
  sky130_fd_sc_hd__nand2_1 g2856(.A (n_33), .B (op[0]), .Y (n_40));
  sky130_fd_sc_hd__inv_1 g2858(.A (n_33), .Y (n_34));
  sky130_fd_sc_hd__clkinv_1 g2860(.A (n_8), .Y (n_32));
  sky130_fd_sc_hd__clkbuf_1 g2861(.A (n_31), .X (n_8));
  sky130_fd_sc_hd__clkbuf_1 g2863(.A (n_29), .X (n_30));
  sky130_fd_sc_hd__nand2_1 g2864(.A (n_16), .B (b[2]), .Y (n_28));
  sky130_fd_sc_hd__nand2_1 g2866(.A (op[2]), .B (op[1]), .Y (n_36));
  sky130_fd_sc_hd__nand2_2 g2867(.A (n_4), .B (n_13), .Y (n_35));
  sky130_fd_sc_hd__nor2_1 g2868(.A (op[1]), .B (op[2]), .Y (n_33));
  sky130_fd_sc_hd__nand2_1 g2869(.A (a[0]), .B (b[0]), .Y (n_31));
  sky130_fd_sc_hd__nor2_2 g2870(.A (b[3]), .B (b[2]), .Y (n_29));
  sky130_fd_sc_hd__inv_1 g2872(.A (n_22), .Y (n_21));
  sky130_fd_sc_hd__nor2_1 g2873(.A (n_13), .B (n_5), .Y (n_20));
  sky130_fd_sc_hd__nand2_1 g2874(.A (a[3]), .B (b[3]), .Y (n_27));
  sky130_fd_sc_hd__nand2_1 g2875(.A (n_14), .B (a[2]), .Y (n_26));
  sky130_fd_sc_hd__nor2b_1 g2876(.A (op[1]), .B_N (op[2]), .Y (n_25));
  sky130_fd_sc_hd__nand2_1 g2877(.A (n_5), .B (a[1]), .Y (n_24));
  sky130_fd_sc_hd__nor2_2 g2878(.A (a[0]), .B (n_12), .Y (n_23));
  sky130_fd_sc_hd__nand2_2 g2879(.A (n_19), .B (op[1]), .Y (n_22));
  sky130_fd_sc_hd__inv_2 g2880(.A (op[2]), .Y (n_19));
  sky130_fd_sc_hd__inv_2 g2881(.A (op[0]), .Y (n_18));
  sky130_fd_sc_hd__inv_1 g2882(.A (n_7), .Y (n_17));
  sky130_fd_sc_hd__buf_1 g2884(.A (a[2]), .X (n_7));
  sky130_fd_sc_hd__inv_2 g2885(.A (a[2]), .Y (n_16));
  sky130_fd_sc_hd__inv_1 g2887(.A (b[3]), .Y (n_15));
  sky130_fd_sc_hd__inv_2 g2888(.A (b[2]), .Y (n_14));
  sky130_fd_sc_hd__clkbuf_1 g2890(.A (b[2]), .X (n_6));
  sky130_fd_sc_hd__inv_2 g2892(.A (a[1]), .Y (n_13));
  sky130_fd_sc_hd__inv_2 g2893(.A (b[0]), .Y (n_12));
  sky130_fd_sc_hd__clkinv_1 g2894(.A (a[3]), .Y (n_11));
  sky130_fd_sc_hd__inv_2 fopt2898(.A (n_5), .Y (n_4));
  sky130_fd_sc_hd__buf_4 fopt2899(.A (b[1]), .X (n_5));
  sky130_fd_sc_hd__and2_2 g2(.A (n_26), .B (n_28), .X (n_3));
  sky130_fd_sc_hd__nand2b_1 g2900(.A_N (n_31), .B (n_35), .Y (n_2));
  sky130_fd_sc_hd__a21boi_2 g2901(.A1 (n_78), .A2 (n_3), .B1_N (n_26),
       .Y (n_1));
  sky130_fd_sc_hd__nand2b_1 g2902(.A_N (a[0]), .B (n_12), .Y (n_0));
endmodule

module synth_wrapper(clk, rst_n, a, b, op, result, carry);
  input clk, rst_n;
  input [3:0] a, b;
  input [2:0] op;
  output [3:0] result;
  output carry;
  wire clk, rst_n;
  wire [3:0] a, b;
  wire [2:0] op;
  wire [3:0] result;
  wire carry;
  wire [3:0] a_reg;
  wire [3:0] b_reg;
  wire [2:0] op_reg;
  wire UNCONNECTED, UNCONNECTED0, UNCONNECTED1, UNCONNECTED2,
       carry_reg_70, n_0, n_1, n_2;
  wire n_3, n_4, n_5, n_6, n_8, n_9, n_10, n_11;
  wire n_12, n_13, n_14, n_15, n_16, n_17, n_18, n_19;
  wire n_20, n_21, n_22, n_23, n_24, n_25, n_26, n_27;
  wire n_28, n_29, n_30, n_31, n_32, n_33, n_34, \result_reg[0]_58 ;
  wire \result_reg[1]_59 , \result_reg[2]_60 , \result_reg[3]_61 ;
  alu alu(.clk (clk), .rst_n (1'b0), .a (a_reg), .b (b_reg), .op
       (op_reg), .result ({\result_reg[3]_61 , \result_reg[2]_60 ,
       \result_reg[1]_59 , \result_reg[0]_58 }), .carry (carry_reg_70));
  sky130_fd_sc_hd__dfbbp_1 \b_reg_reg[1] (.RESET_B (n_20), .SET_B
       (n_23), .CLK (clk), .D (b[1]), .Q (UNCONNECTED), .Q_N (n_28));
  sky130_fd_sc_hd__dfbbp_1 \b_reg_reg[0] (.RESET_B (n_13), .SET_B
       (n_22), .CLK (clk), .D (b[0]), .Q (UNCONNECTED0), .Q_N (n_27));
  sky130_fd_sc_hd__dfbbp_1 \a_reg_reg[0] (.RESET_B (n_5), .SET_B (n_9),
       .CLK (clk), .D (a[0]), .Q (UNCONNECTED1), .Q_N (n_31));
  sky130_fd_sc_hd__dfbbp_1 \b_reg_reg[2] (.RESET_B (n_21), .SET_B
       (n_19), .CLK (clk), .D (b[2]), .Q (b_reg[2]), .Q_N (n_29));
  sky130_fd_sc_hd__dfbbp_1 \b_reg_reg[3] (.RESET_B (n_18), .SET_B
       (n_17), .CLK (clk), .D (b[3]), .Q (b_reg[3]), .Q_N (n_30));
  sky130_fd_sc_hd__dfbbp_1 \op_reg_reg[0] (.RESET_B (n_1), .SET_B
       (n_16), .CLK (clk), .D (op[0]), .Q (op_reg[0]), .Q_N (n_24));
  sky130_fd_sc_hd__dfbbp_1 \op_reg_reg[1] (.RESET_B (n_10), .SET_B
       (n_11), .CLK (clk), .D (op[1]), .Q (op_reg[1]), .Q_N (n_25));
  sky130_fd_sc_hd__dfbbp_1 \op_reg_reg[2] (.RESET_B (n_14), .SET_B
       (n_12), .CLK (clk), .D (op[2]), .Q (op_reg[2]), .Q_N (n_26));
  sky130_fd_sc_hd__dfbbp_1 \a_reg_reg[1] (.RESET_B (n_8), .SET_B (n_6),
       .CLK (clk), .D (a[1]), .Q (UNCONNECTED2), .Q_N (n_32));
  sky130_fd_sc_hd__dfbbp_1 \a_reg_reg[2] (.RESET_B (n_4), .SET_B (n_3),
       .CLK (clk), .D (a[2]), .Q (a_reg[2]), .Q_N (n_33));
  sky130_fd_sc_hd__dfbbp_1 \a_reg_reg[3] (.RESET_B (n_15), .SET_B
       (n_2), .CLK (clk), .D (a[3]), .Q (a_reg[3]), .Q_N (n_34));
  sky130_fd_sc_hd__dfrtp_1 carry_reg(.RESET_B (rst_n), .CLK (clk), .D
       (carry_reg_70), .Q (carry));
  sky130_fd_sc_hd__dfrtp_1 \result_reg[2] (.RESET_B (rst_n), .CLK
       (clk), .D (\result_reg[2]_60 ), .Q (result[2]));
  sky130_fd_sc_hd__dfrtp_1 \result_reg[0] (.RESET_B (rst_n), .CLK
       (clk), .D (\result_reg[0]_58 ), .Q (result[0]));
  sky130_fd_sc_hd__dfrtp_1 \result_reg[1] (.RESET_B (rst_n), .CLK
       (clk), .D (\result_reg[1]_59 ), .Q (result[1]));
  sky130_fd_sc_hd__dfrtp_1 \result_reg[3] (.RESET_B (rst_n), .CLK
       (clk), .D (\result_reg[3]_61 ), .Q (result[3]));
  sky130_fd_sc_hd__nand2_1 g292(.A (n_0), .B (b[1]), .Y (n_23));
  sky130_fd_sc_hd__nand2_1 g293(.A (n_0), .B (b[0]), .Y (n_22));
  sky130_fd_sc_hd__or2_1 g294(.A (b[2]), .B (rst_n), .X (n_21));
  sky130_fd_sc_hd__or2_1 g295(.A (b[1]), .B (rst_n), .X (n_20));
  sky130_fd_sc_hd__nand2_1 g296(.A (n_0), .B (b[2]), .Y (n_19));
  sky130_fd_sc_hd__or2_1 g297(.A (b[3]), .B (rst_n), .X (n_18));
  sky130_fd_sc_hd__nand2_1 g298(.A (n_0), .B (b[3]), .Y (n_17));
  sky130_fd_sc_hd__nand2_1 g299(.A (n_0), .B (op[0]), .Y (n_16));
  sky130_fd_sc_hd__or2_1 g300(.A (a[3]), .B (rst_n), .X (n_15));
  sky130_fd_sc_hd__or2_1 g301(.A (op[2]), .B (rst_n), .X (n_14));
  sky130_fd_sc_hd__or2_1 g302(.A (b[0]), .B (rst_n), .X (n_13));
  sky130_fd_sc_hd__nand2_1 g303(.A (n_0), .B (op[2]), .Y (n_12));
  sky130_fd_sc_hd__nand2_1 g304(.A (n_0), .B (op[1]), .Y (n_11));
  sky130_fd_sc_hd__or2_1 g305(.A (op[1]), .B (rst_n), .X (n_10));
  sky130_fd_sc_hd__nand2_1 g306(.A (n_0), .B (a[0]), .Y (n_9));
  sky130_fd_sc_hd__or2_1 g307(.A (a[1]), .B (rst_n), .X (n_8));
  sky130_fd_sc_hd__nand2_1 g308(.A (n_0), .B (a[1]), .Y (n_6));
  sky130_fd_sc_hd__or2_1 g309(.A (a[0]), .B (rst_n), .X (n_5));
  sky130_fd_sc_hd__or2_1 g310(.A (a[2]), .B (rst_n), .X (n_4));
  sky130_fd_sc_hd__nand2_1 g311(.A (n_0), .B (a[2]), .Y (n_3));
  sky130_fd_sc_hd__nand2_1 g312(.A (n_0), .B (a[3]), .Y (n_2));
  sky130_fd_sc_hd__or2_1 g313(.A (op[0]), .B (rst_n), .X (n_1));
  sky130_fd_sc_hd__clkinv_1 g315(.A (n_31), .Y (a_reg[0]));
  sky130_fd_sc_hd__clkinv_1 g316(.A (n_32), .Y (a_reg[1]));
  sky130_fd_sc_hd__inv_2 g319(.A (rst_n), .Y (n_0));
  sky130_fd_sc_hd__clkinv_1 g320(.A (n_28), .Y (b_reg[1]));
  sky130_fd_sc_hd__inv_2 g324(.A (n_27), .Y (b_reg[0]));
endmodule

